language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq geoip-database
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=proxylist.test_settings
install:
  - pip install -e . --use-mirrors
  - pip install -r requirements/tests.txt Django==$DJANGO --use-mirrors
before_script:
  - flake8 --exclude=migrations --ignore="W801,W402,F401" proxylist
script:
  - coverage run --branch --source=proxylist `which django-admin.py` test proxylist
  - coverage report --omit="proxylist/test*,proxylist/migrations/*,proxylist/management/*"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6
branches:
  only:
    - master
    - development
after_success: coveralls
